# Generated by Django 3.2.4 on 2021-08-04 22:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='order_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town',
            new_name='town_or_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=1.0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=40),
        ),
    ]
