# Generated by Django 3.2.4 on 2021-08-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='description',
            new_name='email',
        ),
    ]
