# Generated by Django 3.2.4 on 2021-08-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
